CREATE TABLE open_source_repo
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_name VARCHAR(512) NOT NULL,
    repo_name  VARCHAR(512) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT now(),
    updated_at TIMESTAMP(6),
    clone_url  VARCHAR(512) NOT NULL,

    CONSTRAINT uq_repo UNIQUE (owner_name, repo_name)
);

CREATE TABLE open_source_repo_file
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at         TIMESTAMP(6) NOT NULL DEFAULT now(),
    updated_at         TIMESTAMP(6),
    path               VARCHAR(512) NOT NULL,
    name               VARCHAR(512) NOT NULL,
    repo_file_type     VARCHAR(32)  NOT NULL,
    extension          VARCHAR(200) NOT NULL DEFAULT '',
    raw_text           TEXT,
    origin             VARCHAR(100),
    opensource_repo_id BIGINT       NOT NULL,

    CONSTRAINT fk_repo_file_repo
        FOREIGN KEY (opensource_repo_id)
            REFERENCES open_source_repo (id),

    CONSTRAINT uq_repo_file UNIQUE (opensource_repo_id, path)
);

CREATE TABLE type
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at              TIMESTAMP(6) NOT NULL DEFAULT now(),
    updated_at              TIMESTAMP(6),
    type_internal_name      VARCHAR(512) NOT NULL,
    type_kind               VARCHAR(255),
    super_type_id           BIGINT,
    origin                  VARCHAR(255) NOT NULL,
    opensource_repo_file_id BIGINT,
    opensource_repo_id      BIGINT       NOT NULL,

    CONSTRAINT fk_type_file
        FOREIGN KEY (opensource_repo_file_id)
            REFERENCES open_source_repo_file (id),

    CONSTRAINT fk_type_repo
        FOREIGN KEY (opensource_repo_id)
            REFERENCES open_source_repo (id),

    CONSTRAINT fk_type_super
        FOREIGN KEY (super_type_id)
            REFERENCES type (id),

    CONSTRAINT uq_type UNIQUE (opensource_repo_id, type_internal_name)
);

CREATE TABLE type_implementation
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at          TIMESTAMP(6) NOT NULL DEFAULT now(),
    updated_at          TIMESTAMP(6),
    implemented_type_id BIGINT       NOT NULL,
    interface_type_id   BIGINT       NOT NULL,

    CONSTRAINT fk_impl_type
        FOREIGN KEY (implemented_type_id)
            REFERENCES type (id),

    CONSTRAINT fk_impl_interface
        FOREIGN KEY (interface_type_id)
            REFERENCES type (id),

    CONSTRAINT uq_type_impl UNIQUE (implemented_type_id, interface_type_id)
);

CREATE TABLE method
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at       TIMESTAMP(6) NOT NULL DEFAULT now(),
    updated_at       TIMESTAMP(6),
    method_name      VARCHAR(255),
    return_type      VARCHAR(300),
    argument_types   JSONB,
    method_modifiers JSONB,
    method_signature VARCHAR(512) NOT NULL,
    start_line       INT,
    end_line         INT,
    origin           VARCHAR(300),
    type_id          BIGINT       NOT NULL,

    CONSTRAINT uq_method UNIQUE (type_id, method_signature),

    CONSTRAINT fk_method_type
        FOREIGN KEY (type_id)
            REFERENCES type (id)
);

CREATE TABLE method_call_edge
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL DEFAULT now(),
    updated_at TIMESTAMP(6),
    caller_id  BIGINT       NOT NULL,
    callee_id  BIGINT       NOT NULL,

    CONSTRAINT fk_edge_caller
        FOREIGN KEY (caller_id)
            REFERENCES method (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_edge_callee
        FOREIGN KEY (callee_id)
            REFERENCES method (id),

    CONSTRAINT uq_call UNIQUE (caller_id, callee_id)
);