CREATE TABLE users
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id BIGINT,
    role        VARCHAR(50),
    user_name   VARCHAR(100),
    login_name  VARCHAR(100),
    email       VARCHAR(255),
    password    VARCHAR(255),
    avatar_url  VARCHAR(500),
    disabled    BOOLEAN,
    created_at  TIMESTAMP(6) NOT NULL,
    updated_at  TIMESTAMP(6)
);


CREATE TABLE refresh_token
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL,
    token       VARCHAR(255) NOT NULL,
    expiry_date TIMESTAMP(6) NOT NULL,
    created_at  TIMESTAMP(6) NOT NULL,
    updated_at  TIMESTAMP(6),

    CONSTRAINT fk_refresh_token_user
        FOREIGN KEY (user_id)
            REFERENCES users (id)
);