CREATE TABLE issues
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    dtype         VARCHAR(31)  NOT NULL,

    created_at    TIMESTAMP(6),
    updated_at    TIMESTAMP(6),

    provider_id   BIGINT,
    tag_id        INT,

    author_id     BIGINT       NOT NULL,
    repository_id BIGINT       NOT NULL,

    title         VARCHAR(255) NOT NULL,
    body          TEXT,

    is_opened     BOOLEAN      NOT NULL,
    comment_count INT          NOT NULL,
    disabled      BOOLEAN      NOT NULL DEFAULT FALSE,

    review_count  INT,

    CONSTRAINT fk_issue_author
        FOREIGN KEY (author_id)
            REFERENCES users (id),

    CONSTRAINT fk_issue_repository
        FOREIGN KEY (repository_id)
            REFERENCES open_source_repo (id)
);

CREATE TABLE issue_comments
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    created_at  TIMESTAMP(6),
    updated_at  TIMESTAMP(6),

    provider_id BIGINT,

    author_id   BIGINT NOT NULL,
    issue_id    BIGINT NOT NULL,

    body        TEXT,

    CONSTRAINT fk_issue_comment_author
        FOREIGN KEY (author_id)
            REFERENCES users (id),

    CONSTRAINT fk_issue_comment_issue
        FOREIGN KEY (issue_id)
            REFERENCES issues (id)
);


CREATE TABLE reviews
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    provider_id  BIGINT       NOT NULL,
    submitted_at TIMESTAMP(6),

    author_id    BIGINT       NOT NULL,
    pull_id      BIGINT       NOT NULL,

    body         VARCHAR(255) NOT NULL,

    CONSTRAINT fk_review_author
        FOREIGN KEY (author_id)
            REFERENCES users (id),

    CONSTRAINT fk_review_pull
        FOREIGN KEY (pull_id)
            REFERENCES issues (id)
);

CREATE TABLE pull_comments
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),

    author_id  BIGINT       NOT NULL,
    review_id  BIGINT       NOT NULL,

    diff_hunk  TEXT         NOT NULL,
    body       TEXT         NOT NULL,
    path       VARCHAR(255) NOT NULL,

    CONSTRAINT fk_pull_comment_author
        FOREIGN KEY (author_id)
            REFERENCES users (id),

    CONSTRAINT fk_pull_comment_review
        FOREIGN KEY (review_id)
            REFERENCES reviews (id)
);

CREATE TABLE labels
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    repository_id BIGINT       NOT NULL,
    issue_id      BIGINT       NOT NULL,

    name          VARCHAR(255) NOT NULL,
    color_code    VARCHAR(255) NOT NULL,
    description   VARCHAR(255),

    CONSTRAINT fk_label_repository
        FOREIGN KEY (repository_id)
            REFERENCES open_source_repo (id),

    CONSTRAINT fk_label_issue
        FOREIGN KEY (issue_id)
            REFERENCES issues (id)
);